# Results LaTeX table generation script

In [1]:
import json

import pandas as pd
import numpy as np

from llm_audit import BASE_DIR


FACTOR_ORDER = ["AGR", "SUB", "CONV"]

OLMO_ORDER = {
    "Olmo 3.1 32B": 0,
    "Olmo3 7B Base": 1,
    "Olmo3 7B Instruct SFT": 2,
    "Olmo3 7B Instruct DPO": 3,
    "Olmo3 7B Instruct RLVR": 4,
}

# Load models
with open(BASE_DIR / "resources" / "input" / "models" / "final_complete.json", "r") as f:
    models = json.load(f)
models.sort(key=lambda m: (m["group"], m["name_short"]))

model_labels = [model["name"] for model in models]

model_labels_short_map = {model["name"]: model["name_short"] for model in models}
model_labels_group_map = {model["name"]: model["group"] for model in models}

In [2]:
# 1. Color palette (101 colors, 0% -> 50% -> 100%)
_ANCHORS = [
    (0, (0xF7, 0xF7, 0xF7)),  # white @ 0.0
    (50, (0xF4, 0xA5, 0x82)),  # salmon @ 0.5
    (100, (0xCA, 0x00, 0x20)),
]  # red @ 1.0


def _build_palette():
    palette = {}
    for i in range(len(_ANCHORS) - 1):
        p0, c0 = _ANCHORS[i]
        p1, c1 = _ANCHORS[i + 1]
        for pct in range(p0, p1 + 1):
            t = (pct - p0) / (p1 - p0)
            rgb = tuple(int(round(c0[j] + t * (c1[j] - c0[j]))) for j in range(3))
            palette[pct] = "{:02X}{:02X}{:02X}".format(*rgb)
    return palette


PALETTE = _build_palette()


def _cell_color(hex_code):
    return r"\cellcolor[HTML]{" + hex_code + r"}"


def _color_for_value(x):
    if x < 0:
        return _cell_color("F7F7F7")
    pct = int(round(min(max(x, 0.0), 100.0)))
    return _cell_color(PALETTE[pct])


def _parse_point(cell_str):
    try:
        return float(str(cell_str).split()[0])
    except (ValueError, IndexError):
        return -1.0


def _fmt_cell(cell_str: str, col_maxes: tuple[float, float, float] = (100.0, 100.0, 100.0)) -> tuple[float, str]:
    try:
        parts = str(cell_str).replace("[", "").replace("]", "").replace(",", "").split()
        nums = [float(p) for p in parts]
        nums = [min(max(num * 100, 0.0), 100.0) for num in nums]
        x = nums[0]

        def pad(v, col_max):
            s = f"{v:.1f}"
            if col_max >= 100.0:
                # reference is 100.0 (5 chars): X.Y needs 2 phantoms, XX.Y needs 1
                if v < 10.0:
                    return r"\phantom{0}" * 2 + s
                elif v < 100.0:
                    return r"\phantom{0}" + s
                else:
                    return s
            elif col_max >= 10.0:
                # reference is XX.Y (4 chars): X.Y needs 1 phantom
                if v < 10.0:
                    return r"\phantom{0}" + s
                else:
                    return s
            else:
                # reference is X.Y (3 chars): no phantoms needed
                return s

        fmt = (
            rf"{pad(nums[0], col_maxes[0])} [{pad(nums[1], col_maxes[1])} {pad(nums[2], col_maxes[2])}]"
            if len(nums) == 3
            else pad(x, col_maxes[0])
        )
        return x, fmt
    except (ValueError, IndexError):
        return -1.0, str(cell_str)


def _col_maxes(df: pd.DataFrame, col: str) -> tuple[float, float, float]:
    """Max scaled value per position (point, lo, hi) across all rows."""
    maxes = [0.0, 0.0, 0.0]
    for cell in df[col]:
        try:
            parts = str(cell).replace("[", "").replace("]", "").replace(",", "").split()
            nums = [min(max(float(p) * 100, 0.0), 100.0) for p in parts]
            for i in range(3):
                maxes[i] = max(maxes[i], nums[i])
        except (ValueError, IndexError):
            pass
    return (maxes[0], maxes[1], maxes[2])


def _colored_cell(row, col, col_maxes=(100.0, 100.0, 100.0)):
    x, val_str = _fmt_cell(row[col], col_maxes)
    return f"{_color_for_value(x)}{val_str}"


# 2. Simple table (no factor column)
def _build_simple(df, value_cols):
    col_spec = "ll" + "c" * len(value_cols)
    lines = [
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        "Group & Model & " + " & ".join(value_cols) + r" \\",
        r"\midrule",
    ]
    col_maxes = {c: _col_maxes(df, c) for c in value_cols}
    for group_name, gdf in df.groupby("group", sort=False):
        gdf = gdf.reset_index(drop=True)
        n = len(gdf)
        for i, (_, row) in enumerate(gdf.iterrows()):
            prefix = rf"\multirow{{{n}}}{{*}}{{{group_name}}}" if i == 0 else ""
            cells = [prefix, row["model"]] + [_colored_cell(row, c, col_maxes[c]) for c in value_cols]
            lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return lines


# 3. Factor table (with factor column -> multicolumn header)
def _build_factor(df, value_cols):
    factors = list(dict.fromkeys(df["factor"]))  # preserve order, deduplicate
    n_vc = len(value_cols)
    # col_spec: group | model | (value_cols × factors), vertical rules between factors
    col_spec = "ll" + ("|" + "c" * n_vc) * len(factors)

    # Header row 1: factor multicolumns
    factor_headers = " & ".join(rf"\multicolumn{{{n_vc}}}{{c}}{{{f}}}" for f in factors)
    header1 = r" & & " + factor_headers + r" \\"

    # Header row 2: value col names repeated
    header2 = " & & " + " & ".join(list(value_cols) * len(factors)) + r" \\"

    # Cmidrule under each factor label
    cmidrules = []
    for fi, _ in enumerate(factors):
        start = 3 + fi * n_vc  # 1-indexed; cols 1=group, 2=model, then values
        end = start + n_vc - 1
        cmidrules.append(rf"\cmidrule(lr){{{start}-{end}}}")
    cmidrule_line = " ".join(cmidrules)

    lines = [
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        header1,
        cmidrule_line,
        header2,
        r"\midrule",
    ]

    # Pivot: one row per (group, model), columns = (factor, value_col)
    pivot = df.pivot_table(
        index=["group", "model"], columns="factor", values=value_cols, aggfunc="first", observed=False
    )
    # Restore original group/model order
    order = df[["group", "model"]].drop_duplicates()

    # Group sizes (models per group)
    group_sizes = order.groupby("group", sort=False)["model"].count()

    factor_col_maxes = {factor: {} for factor in factors}
    for factor in factors:
        factor_col_maxes[factor] = {c: _col_maxes(df[df["factor"] == factor].copy(), c) for c in value_cols}

    for group_name, gdf_order in order.groupby("group", sort=False):
        n = group_sizes[group_name]
        for i, (_, meta) in enumerate(gdf_order.iterrows()):
            model = meta["model"]
            prefix = rf"\multirow{{{n}}}{{*}}{{{group_name}}}" if i == 0 else ""
            data_cells = []
            for factor in factors:
                for vc in value_cols:
                    try:
                        raw_val = pivot.loc[(group_name, model), (vc, factor)]
                        x, val_str = _fmt_cell(raw_val, factor_col_maxes[factor][vc])
                    except KeyError:
                        _, val_str = -1.0, "--"
                    data_cells.append(f"{_color_for_value(x)}{val_str}")
            cells = [prefix, model] + data_cells
            lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\midrule")

    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return lines


# 4. Entry point
def df_to_latex(
    df: pd.DataFrame,
    caption: str = "Results",
    label: str = "tab:results",
    fit: str = "auto",  # "auto" | "rotate" | "resize" | "none"
) -> str:
    """
    fit="auto"   → rotate if factor column present, else none
    fit="rotate" → sidewaystable (requires \\usepackage{rotating})
    fit="resize" → resizebox to \\textwidth (font shrinks)
    fit="none"   → no adjustment
    """
    has_factor = "factor" in df.columns
    value_cols = [c for c in df.columns if c not in ("factor", "group", "model")]

    if fit == "auto":
        fit = "resize" if has_factor else "none"

    body = _build_factor(df, value_cols) if has_factor else _build_simple(df, value_cols)

    float_env = "sidewaystable" if fit == "rotate" else "table"

    inner = [
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\setlength{\tabcolsep}{4pt}",
    ]

    if fit == "resize":
        inner += [r"\resizebox{\textwidth}{!}{%", *body, r"}"]
    else:
        inner += body

    return "\n".join(
        [
            rf"\begin{{{float_env}}}[ht]",
            *inner,
            rf"\end{{{float_env}}}",
        ]
    )

## Closed

In [3]:
df = pd.read_parquet(BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "closed__across_datasets.parquet")
df["group"] = df["model"].map(model_labels_group_map)
df["model"] = df["model"].map(model_labels_short_map)
df_filtered = df[
    (df["experiment_type"] == "closed_question") & (df["language"] == "en") & (df["experiment_ablation"] == "default")
]
df_filtered = df_filtered.drop(columns=["experiment_type", "language", "experiment_ablation"])
df_filtered = df_filtered.rename(columns={"auth": "ARR"})
df_filtered = df_filtered[["group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_1d_closed = df_filtered  # .round(2)

In [4]:
df = pd.read_parquet(BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "closed__per_factor_across_datasets.parquet")
df["group"] = df["model"].map(model_labels_group_map)
df["model"] = df["model"].map(model_labels_short_map)
df["factor"] = pd.Categorical(df["factor"], categories=FACTOR_ORDER, ordered=True)
df_filtered = df[
    (df["experiment_type"] == "closed_question")
    & (df["language"] == "en")
    & (df["experiment_ablation"] == "default")
    & (df["factor"].isin(["AGR", "SUB", "CONV"]))
]
df_filtered = df_filtered.drop(columns=["experiment_type", "language", "experiment_ablation"])
df_filtered = df_filtered.rename(columns={"auth": "ARR"})
df_filtered = df_filtered[["factor", "group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["factor", "group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_3d_closed = df_filtered  # .round(2)

## Open

In [5]:
df = pd.read_parquet(BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "open_adjusted__across_datasets.parquet")
df["group"] = df["model"].map(model_labels_group_map)
df["model"] = df["model"].map(model_labels_short_map)
df_filtered = df[
    (df["experiment_type"] == "open_question") & (df["language"] == "en") & (df["experiment_ablation"] == "default")
]
df_filtered = df_filtered.drop(columns=["experiment_type", "language", "experiment_ablation"])
df_filtered = df_filtered.rename(columns={"auth_adj": "ARR"})
df_filtered = df_filtered[["group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_1d_open = df_filtered  # .round(2)

In [6]:
df = pd.read_parquet(
    BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "open_adjusted__per_factor_across_datasets.parquet"
)
df["group"] = df["model"].map(model_labels_group_map)
df["model"] = df["model"].map(model_labels_short_map)
df["factor"] = pd.Categorical(df["factor"], categories=FACTOR_ORDER, ordered=True)
df_filtered = df[
    (df["experiment_type"] == "open_question")
    & (df["language"] == "en")
    & (df["experiment_ablation"] == "default")
    & (df["factor"].isin(["AGR", "SUB", "CONV"]))
]
df_filtered = df_filtered.drop(columns=["experiment_type", "language", "experiment_ablation"])
df_filtered = df_filtered.rename(columns={"auth_adj": "ARR"})
df_filtered = df_filtered[["factor", "group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["factor", "group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_3d_open = df_filtered  # .round(2)

## Behavioral

In [7]:
df = pd.read_parquet(BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "vignettes__across_datasets.parquet")
print(df.columns)
df["group"] = df["model"].map(model_labels_group_map)
df["model"] = df["model"].map(model_labels_short_map)
df_filtered = df[(df["language"] == "en") & (df["experiment_ablation"] == "default")]
df_filtered = df_filtered.drop(columns=["language", "experiment_ablation"])
df_filtered = df_filtered.rename(columns={"auth": "ARR"})
df_filtered = df_filtered[["group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_1d_behavioral = df_filtered  # .round(2)

Index(['model', 'language', 'experiment_ablation', 'auth', 'ci_low',
       'ci_high'],
      dtype='object')

In [8]:
df = pd.read_parquet(BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "vignettes__per_factor_across_datasets.parquet")
df["group"] = df["model"].map(model_labels_group_map)
df["model"] = df["model"].map(model_labels_short_map)
df["factor"] = pd.Categorical(df["factor"], categories=FACTOR_ORDER, ordered=True)
df_filtered = df[
    (df["language"] == "en") & (df["experiment_ablation"] == "default") & (df["factor"].isin(["AGR", "SUB", "CONV"]))
]
df_filtered = df_filtered.drop(columns=["language", "experiment_ablation"])
df_filtered = df_filtered.rename(columns={"auth": "ARR"})
df_filtered = df_filtered[["factor", "group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["factor", "group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_3d_behavioral = df_filtered  # .round(2)

## Realsitic

In [9]:
df = pd.read_parquet(
    BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "default_issuebench_gemma4sft" / "issuebench__cis.parquet"
)
df.head()

,dimension,quantification_method,judge_positive_rate,n,n_valid,n_refusal,generating_model_name,ci_low,ci_high,adjusted_positive_rate,adjustment_tpr,adjustment_fpr,adjusted_ci_low,adjusted_ci_high
0,aggression,judge_count,0.003148,1000,953,47,Qwen/Qwen3-30B-A3B-Instruct-2507,0.000000,0.007292,0.007572,0.396215,0.000000,0.000000,0.028000
1,submission,judge_count,0.013641,1000,953,47,Qwen/Qwen3-30B-A3B-Instruct-2507,0.007284,0.021831,0.001540,0.631298,0.012046,0.000000,0.040000
2,conventionalism,judge_count,0.008395,1000,953,47,Qwen/Qwen3-30B-A3B-Instruct-2507,0.003128,0.014737,0.023916,0.334499,0.000000,0.007000,0.090525
3,refusal,judge_count,0.047000,1000,1000,47,Qwen/Qwen3-30B-A3B-Instruct-2507,0.035000,0.060000,NaN,NaN,0.000000,NaN,NaN
4,any,judge_count,0.020986,1000,953,47,Qwen/Qwen3-30B-A3B-Instruct-2507,0.012577,0.030400,0.034335,0.582494,0.000000,0.018352,0.066517

In [10]:
df = pd.read_parquet(
    BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "default_issuebench_gemma4sft" / "issuebench__cis.parquet"
)
df["group"] = df["generating_model_name"].map(model_labels_group_map)
df["model"] = df["generating_model_name"].map(model_labels_short_map)
df_filtered = df[(df["dimension"] == "any") & (df["quantification_method"] == "judge_count")]
df_filtered = df_filtered.drop(
    columns=[
        "dimension",
        "quantification_method",
        "judge_positive_rate",
        "n",
        "n_valid",
        "n_refusal",
        "generating_model_name",
        "ci_low",
        "ci_high",
        "adjustment_tpr",
        "adjustment_fpr",
    ]
)
df_filtered = df_filtered.rename(
    columns={"adjusted_positive_rate": "ARR", "adjusted_ci_low": "ci_low", "adjusted_ci_high": "ci_high"}
)
df_filtered = df_filtered[["group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_1d_realistic = df_filtered  # .round(2)

In [11]:
factor_mapping = {"aggression": "AGR", "submission": "SUB", "conventionalism": "CONV"}

df = pd.read_parquet(
    BASE_DIR / "eval" / "data" / "boot" / "pipeline" / "default_issuebench_gemma4sft" / "issuebench__cis.parquet"
)
df["group"] = df["generating_model_name"].map(model_labels_group_map)
df["model"] = df["generating_model_name"].map(model_labels_short_map)

df_filtered = df[df["dimension"].isin(factor_mapping.keys())].copy()
df_filtered["factor"] = df_filtered["dimension"].map(factor_mapping)
df_filtered = df_filtered[(df_filtered["quantification_method"] == "judge_count")]
df_filtered = df_filtered.drop(
    columns=[
        "dimension",
        "quantification_method",
        "judge_positive_rate",
        "n",
        "n_valid",
        "n_refusal",
        "generating_model_name",
        "ci_low",
        "ci_high",
        "adjustment_tpr",
        "adjustment_fpr",
    ]
)
df_filtered = df_filtered.rename(
    columns={"adjusted_positive_rate": "ARR", "adjusted_ci_low": "ci_low", "adjusted_ci_high": "ci_high"}
)
df_filtered = df_filtered[["factor", "group", "model", "ARR", "ci_low", "ci_high"]]
df_filtered = (
    df_filtered.assign(
        is_olmo=df_filtered["model"].isin(OLMO_ORDER), olmo_rank=df_filtered["model"].map(OLMO_ORDER).fillna(-1)
    )
    .sort_values(by=["factor", "group", "is_olmo", "olmo_rank", "model"])
    .drop(columns=["is_olmo", "olmo_rank"])
    .reset_index(drop=True)
)
df_3d_realistic = df_filtered  # .round(2)

## 1d results
columns: group - model - ARR - ci_low - ci_high

- df_1d_closed
- df_1d_open
- TODO vignettes
- TODO realistic

In [12]:
df_1d = df_1d_closed[["group", "model"]].copy()
df_1d["Psyc (Closed)"] = (
    df_1d_closed["ARR"].astype(str)
    + " ["
    + df_1d_closed["ci_low"].astype(str)
    + " "
    + df_1d_closed["ci_high"].astype(str)
    + "]"
)
df_1d["Psyc (Open)"] = (
    df_1d_open["ARR"].astype(str)
    + " ["
    + df_1d_open["ci_low"].astype(str)
    + " "
    + df_1d_open["ci_high"].astype(str)
    + "]"
)
df_1d["Behavioral"] = (
    df_1d_behavioral["ARR"].astype(str)
    + " ["
    + df_1d_behavioral["ci_low"].astype(str)
    + " "
    + df_1d_behavioral["ci_high"].astype(str)
    + "]"
)
df_1d["Realistic"] = (
    df_1d_realistic["ARR"].astype(str)
    + " ["
    + df_1d_realistic["ci_low"].astype(str)
    + " "
    + df_1d_realistic["ci_high"].astype(str)
    + "]"
)
df_1d

,group,model,Psyc (Closed),Psyc (Open),Behavioral,Realistic
0,Chinese,Deepseek V3.2,0.25903650432656516 [0.2251064941677154 0.2944...,0.1674196880751678 [0.07374051629245224 0.3571...,0.26416666666666666 [0.2333333333333333 0.3],0.04291892821535198 [0.02307375 0.08267]
1,Chinese,Qwen3 30B-A3B 2507,0.2426120975272281 [0.22304838098515237 0.2620...,0.40042347675660395 [0.25718992663044093 0.794...,0.2525 [0.24166666666666667 0.26666666666666666],0.03433514257228158 [0.018352450980392156 0.06...
2,EU,EuroLLM 9B,0.40840088422315274 [0.35987170494139137 0.454...,0.5207378961424024 [0.3304745202311816 1.04776...,0.30795624826150547 [0.2336449054096113 0.3831...,0.046352442472580135 [0.02659611111111111 0.09...
3,EU,Mistral Large 2512,0.31527604691415434 [0.30116076257028945 0.330...,0.19964613813289053 [0.0845480138751045 0.4215...,0.2802403477548925 [0.26346153846153847 0.2974...,0.027468114057825264 [0.0144 0.0525]
4,Russian,GigaChat 20B-A3B,0.37724615718764387 [0.3404461793811647 0.4155...,0.7899432433092002 [0.5159035412110987 1.58369...,0.2460406495252221 [0.20339743589743592 0.2937...,0.051502713858422366 [0.029329166666666667 0.0...
5,Russian,QVikhr 3 8B,0.3259945065044697 [0.30540174800604225 0.3458...,0.1682303483801327 [0.05961856974492581 0.3423...,0.2225 [0.20833333333333334 0.24166666666666667],0.010300542771684474 [0.002799230769230769 0.0...
6,Russian,T-Pro 2.0,0.3330013504969316 [0.3037181455407381 0.36392...,0.24607622645541716 [0.12264891369956764 0.508...,0.26916666666666667 [0.2333333333333333 0.3083...,0.018884328414754868 [0.007307692307692308 0.0...
7,Russian,YandexGPT 5 Lite 8B,0.38186615062547224 [0.36899761758427674 0.393...,0.1505258912383621 [0.03895625855160794 0.3358...,0.26416666666666666 [0.25 0.2833333333333333],0.02060108554336895 [0.008997222222222222 0.04...
8,USA,Claude Haiku 4.5,0.23088339059822435 [0.21740290156466624 0.245...,0.21391710142278172 [0.10963367489056257 0.423...,0.20402272342074043 [0.1845441595441595 0.2247...,0.012017299900298553 [0.004151785714285715 0.0...
9,USA,GPT5 Mini,0.22843498927897907 [0.2051989632040783 0.2512...,0.2246485471138852 [0.11365760326957183 0.4671...,0.1816342213114754 [0.14513355065986644 0.2203...,0.005150271385842237 [0.0 0.014]
10,USA,Gemini 3 Flash Prev,0.1812562355733038 [0.16990278769074196 0.1941...,0.3097256577096988 [0.18291702623550513 0.6193...,0.21808433533284913 [0.1958905714052773 0.2390...,0.022317842671983026 [0.009599583333333335 0.0...
11,USA,Grok 4.1 Fast,0.28976706752090386 [0.26831420556804186 0.310...,0.5241829264482581 [0.34410226906823144 1.0056...,0.295 [0.26666666666666666 0.325],0.07725407078763355 [0.0478298076923077 0.1410...
12,USA,Olmo 3.1 32B,0.3139094399367579 [0.290604283765963 0.338045...,0.2799887756508747 [0.15052490870502452 0.5551...,0.26166666666666666 [0.2333333333333333 0.2916...,0.012017299900298553 [0.003665909090909091 0.0...
13,USA,Olmo3 7B Base,0.4306633396933284 [0.38195867065972183 0.4819...,0.2477083491703537 [0.11218000755945756 0.4829...,0.3337182338294273 [0.15736832611832613 0.5277...,0.024525101837343986 [0.011971429143474953 0.0...
14,USA,Olmo3 7B Instruct SFT,0.5125948087642 [0.471341779654432 0.553307481...,0.42939078286898263 [0.26569290747581037 0.885...,0.2665411154756064 [0.22195474827053774 0.3152...,0.012017299900298553 [0.00425 0.02700357142857...
15,USA,Olmo3 7B Instruct DPO,0.5158400714428832 [0.48532315126722725 0.5423...,0.3429492983236828 [0.20577913417868707 0.6596...,0.24194526264113894 [0.2126068376068376 0.2724...,0.01545081415752671 [0.006 0.033252083333333335]
16,USA,Olmo3 7B Instruct RLVR,0.5293378856201474 [0.5009774261904719 0.55464...,0.30567420884186597 [0.18610735702914255 0.627...,0.24896196686116337 [0.225 0.27499999999999997],0.013734057028912632 [0.004996153846153846 0.0...

In [13]:
print(df_to_latex(df_1d, caption="1D Results.", label="tab:1d-results", fit="resize"))

\begin{table}[ht]
\centering
\caption{1D Results.}
\label{tab:1d-results}
\setlength{\tabcolsep}{4pt}
\resizebox{\textwidth}{!}{%
\begin{tabular}{llcccc}
\toprule
Group & Model & Psyc (Closed) & Psyc (Open) & Behavioral & Realistic \\
\midrule
\multirow{2}{*}{Chinese} & Deepseek V3.2 & \cellcolor[HTML]{F5CCBA}25.9 [22.5 29.4] & \cellcolor[HTML]{F6DBCF}16.7 [\phantom{0}7.4 \phantom{0}35.7] & \cellcolor[HTML]{F5CCBA}26.4 [23.3 30.0] & \cellcolor[HTML]{F7F0EE}4.3 [2.3 \phantom{0}8.3] \\
 & Qwen3 30B-A3B 2507 & \cellcolor[HTML]{F6D0BF}24.3 [22.3 26.2] & \cellcolor[HTML]{F5B599}40.0 [25.7 \phantom{0}79.5] & \cellcolor[HTML]{F6CEBC}25.2 [24.2 26.7] & \cellcolor[HTML]{F7F2F0}3.4 [1.8 \phantom{0}6.7] \\
\midrule
\multirow{2}{*}{EU} & EuroLLM 9B & \cellcolor[HTML]{F5B497}40.8 [36.0 45.4] & \cellcolor[HTML]{F29E7E}52.1 [33.0 100.0] & \cellcolor[HTML]{F5C4AE}30.8 [23.4 38.3] & \cellcolor[HTML]{F7EFEB}4.6 [2.7 \phantom{0}9.3] \\
 & Mistral Large 2512 & \cellcolor[HTML]{F5C3AC}31.5 [30.1 33.0] & \cellcolor[HTML]{F6D6C8}20.0 [\phantom{0}8.5 \phantom{0}42.2] & \cellcolor[HTML]{F5C9B5}28.0 [26.3 29.7] & \cellcolor[HTML]{F7F2F0}2.7 [1.4 \phantom{0}5.2] \\
\midrule
\multirow{4}{*}{Russian} & GigaChat 20B-A3B & \cellcolor[HTML]{F5B99E}37.7 [34.0 41.6] & \cellcolor[HTML]{DC4549}79.0 [51.6 100.0] & \cellcolor[HTML]{F6CEBC}24.6 [20.3 29.4] & \cellcolor[HTML]{F7EFEB}5.2 [2.9 \phantom{0}9.6] \\
 & QVikhr 3 8B & \cellcolor[HTML]{F5C1AA}32.6 [30.5 34.6] & \cellcolor[HTML]{F6DBCF}16.8 [\phantom{0}6.0 \phantom{0}34.2] & \cellcolor[HTML]{F6D3C4}22.2 [20.8 24.2] & \cellcolor[HTML]{F7F5F5}1.0 [0.3 \phantom{0}2.3] \\
 & T-Pro 2.0 & \cellcolor[HTML]{F5C1AA}33.3 [30.4 36.4] & \cellcolor[HTML]{F6CEBC}24.6 [12.3 \phantom{0}50.8] & \cellcolor[HTML]{F5CBB8}26.9 [23.3 30.8] & \cellcolor[HTML]{F7F4F2}1.9 [0.7 \phantom{0}3.9] \\
 & YandexGPT 5 Lite 8B & \cellcolor[HTML]{F5B99E}38.2 [36.9 39.3] & \cellcolor[HTML]{F6DED4}15.1 [\phantom{0}3.9 \phantom{0}33.6] & \cellcolor[HTML]{F5CCBA}26.4 [25.0 28.3] & \cellcolor[HTML]{F7F4F2}2.1 [0.9 \phantom{0}4.3] \\
\midrule
\multirow{9}{*}{USA} & Claude Haiku 4.5 & \cellcolor[HTML]{F6D1C1}23.1 [21.7 24.5] & \cellcolor[HTML]{F6D5C6}21.4 [11.0 \phantom{0}42.4] & \cellcolor[HTML]{F6D6C8}20.4 [18.5 22.5] & \cellcolor[HTML]{F7F5F5}1.2 [0.4 \phantom{0}2.6] \\
 & GPT5 Mini & \cellcolor[HTML]{F6D1C1}22.8 [20.5 25.1] & \cellcolor[HTML]{F6D3C4}22.5 [11.4 \phantom{0}46.7] & \cellcolor[HTML]{F6D9CD}18.2 [14.5 22.0] & \cellcolor[HTML]{F7F5F5}0.5 [0.0 \phantom{0}1.4] \\
 & Gemini 3 Flash Prev & \cellcolor[HTML]{F6D9CD}18.1 [17.0 19.4] & \cellcolor[HTML]{F5C4AE}31.0 [18.3 \phantom{0}61.9] & \cellcolor[HTML]{F6D3C4}21.8 [19.6 23.9] & \cellcolor[HTML]{F7F4F2}2.2 [1.0 \phantom{0}4.8] \\
 & Grok 4.1 Fast & \cellcolor[HTML]{F5C7B3}29.0 [26.8 31.1] & \cellcolor[HTML]{F29E7E}52.4 [34.4 100.0] & \cellcolor[HTML]{F5C6B1}29.5 [26.7 32.5] & \cellcolor[HTML]{F7EAE4}7.7 [4.8 14.1] \\
 & Olmo 3.1 32B & \cellcolor[HTML]{F5C4AE}31.4 [29.1 33.8] & \cellcolor[HTML]{F5C9B5}28.0 [15.1 \phantom{0}55.5] & \cellcolor[HTML]{F5CCBA}26.2 [23.3 29.2] & \cellcolor[HTML]{F7F5F5}1.2 [0.4 \phantom{0}2.6] \\
 & Olmo3 7B Base & \cellcolor[HTML]{F4B092}43.1 [38.2 48.2] & \cellcolor[HTML]{F6CEBC}24.8 [11.2 \phantom{0}48.3] & \cellcolor[HTML]{F5C1AA}33.4 [15.7 52.8] & \cellcolor[HTML]{F7F4F2}2.5 [1.2 \phantom{0}5.2] \\
 & Olmo3 7B Instruct SFT & \cellcolor[HTML]{F3A280}51.3 [47.1 55.3] & \cellcolor[HTML]{F4B092}42.9 [26.6 \phantom{0}88.6] & \cellcolor[HTML]{F5CBB8}26.7 [22.2 31.5] & \cellcolor[HTML]{F7F5F5}1.2 [0.4 \phantom{0}2.7] \\
 & Olmo3 7B Instruct DPO & \cellcolor[HTML]{F29E7E}51.6 [48.5 54.2] & \cellcolor[HTML]{F5BFA7}34.3 [20.6 \phantom{0}66.0] & \cellcolor[HTML]{F6D0BF}24.2 [21.3 27.2] & \cellcolor[HTML]{F7F4F2}1.5 [0.6 \phantom{0}3.3] \\
 & Olmo3 7B Instruct RLVR & \cellcolor[HTML]{F19B7C}52.9 [50.1 55.5] & \cellcolor[HTML]{F5C4AE}30.6 [18.6 \phantom{0}62.7] & \cellcolor[HTML]{F6CEBC}24.9 [22.5 27.5] & \cellcolor[HTML]{F7F5F5}1.4 [0.5 \phantom{0}3.0] \\
\bottomrule
\end{tabular}
}
\end{table}

## 3d results
columns: factor - group - model - ARR - ci_low - ci_high

- df_3d_closed
- df_3d_open
- TODO vignettes
- TODO realistic

In [14]:
df_3d = df_3d_closed[["factor", "group", "model"]].copy()
df_3d["Psyc (Closed)"] = (
    df_3d_closed["ARR"].astype(str)
    + " ["
    + df_3d_closed["ci_low"].astype(str)
    + " "
    + df_3d_closed["ci_high"].astype(str)
    + "]"
)
df_3d["Psyc (Open)"] = (
    df_3d_open["ARR"].astype(str)
    + " ["
    + df_3d_open["ci_low"].astype(str)
    + " "
    + df_3d_open["ci_high"].astype(str)
    + "]"
)
df_3d["Behavioral"] = (
    df_3d_behavioral["ARR"].astype(str)
    + " ["
    + df_3d_behavioral["ci_low"].astype(str)
    + " "
    + df_3d_behavioral["ci_high"].astype(str)
    + "]"
)
df_3d["Realistic"] = (
    df_3d_realistic["ARR"].astype(str)
    + " ["
    + df_3d_realistic["ci_low"].astype(str)
    + " "
    + df_3d_realistic["ci_high"].astype(str)
    + "]"
)
df_3d

,factor,group,model,Psyc (Closed),Psyc (Open),Behavioral,Realistic
0,AGR,Chinese,Deepseek V3.2,0.21333333333333332 [0.08333333333333334 0.366...,-0.056342448198431615 [-0.20787659482867693 0....,0.48 [0.4 0.55],0.007571643578953835 [0.0 0.02727499999999998]
1,AGR,Chinese,Qwen3 30B-A3B 2507,0.11333333333333333 [0.05 0.18333333333333335],0.11010518661872026 [-0.1118365099312267 0.536...,0.5025 [0.475 0.525],0.007571643578953835 [0.0 0.028]
2,AGR,EU,EuroLLM 9B,0.47021458311092135 [0.30757575757575756 0.633...,0.13784645908824558 [-0.13716926378716085 0.56...,0.4972677595628415 [0.3611111111111111 0.64102...,0.0 [0.0 0.0]
3,AGR,EU,Mistral Large 2512,0.28500000000000003 [0.2833333333333333 0.3],-0.06558953902160672 [-0.23949903815775173 0.0...,0.4601542416452442 [0.41025641025641024 0.4871...,0.010095524771938445 [0.0 0.034999999999999996]
4,AGR,Russian,GigaChat 20B-A3B,0.4013811678517561 [0.3 0.5333333333333333],0.36440018425603565 [-0.019291536825517704 1.0...,0.38974358974358975 [0.3 0.48717948717948717],0.010095524771938445 [0.0 0.03218333333333332]
5,AGR,Russian,QVikhr 3 8B,0.31666666666666665 [0.31666666666666665 0.316...,0.011325226454100579 [-0.17931357876794202 0.1...,0.3575 [0.325 0.4],0.0 [0.0 0.0]
6,AGR,Russian,T-Pro 2.0,0.3516666666666667 [0.2833333333333333 0.46666...,0.04154514913765106 [-0.18358291787072215 0.33...,0.5425 [0.475 0.625],0.0025238811929846113 [0.0 0.012]
7,AGR,Russian,YandexGPT 5 Lite 8B,0.5366666666666667 [0.4833333333333334 0.55],-0.051718902786844066 [-0.21586194710073114 0....,0.515 [0.5 0.525],0.0 [0.0 0.0]
8,AGR,USA,Claude Haiku 4.5,0.10666666666666666 [0.08333333333333333 0.15],0.05924618709125719 [-0.13709996306496194 0.26...,0.28328611898017 [0.2284126984126984 0.3428571...,0.0025238811929846113 [0.0 0.012]
9,AGR,USA,GPT5 Mini,0.15166666666666667 [0.03333333333333333 0.3],0.09623455038395759 [-0.12182910965191697 0.49...,0.325 [0.23321428571428574 0.42424242424242425],0.0 [0.0 0.0]
10,AGR,USA,Gemini 3 Flash Prev,0.013333333333333332 [0.0 0.08333333333333333],-0.09333081149113204 [-0.2643614304801952 -0.0...,0.36454849498327757 [0.3 0.41935483870967744],0.005047762385969223 [0.0 0.02]
11,AGR,USA,Grok 4.1 Fast,0.32999999999999996 [0.21666666666666665 0.416...,0.20719964026205884 [0.00392296865717625 0.545...,0.55 [0.5 0.6],0.027762693122830723 [0.009 0.08068749999999994]
12,AGR,USA,Olmo 3.1 32B,0.27999999999999997 [0.21666666666666665 0.35],-0.07946017525636938 [-0.24641980970342803 0.0...,0.5 [0.425 0.55],0.0 [0.0 0.0]
13,AGR,USA,Olmo3 7B Base,0.4956791306143794 [0.3333333333333333 0.68333...,0.11784574128226413 [-0.1588686555253617 0.575...,0.4605263157894737 [0.125 0.8],0.005546991632933212 [0.0 0.021895034358324694]
14,AGR,USA,Olmo3 7B Instruct SFT,0.6 [0.4333333333333333 0.75],0.008387187563794113 [-0.1654522276974063 0.20...,0.4723756906077348 [0.3783783783783784 0.56756...,0.0 [0.0 0.0]
15,AGR,USA,Olmo3 7B Instruct DPO,0.505 [0.36666666666666664 0.6166666666666667],-0.005483448670968544 [-0.20499644220805902 0....,0.44642857142857145 [0.38461538461538464 0.500...,0.0 [0.0 0.0]
16,AGR,USA,Olmo3 7B Instruct RLVR,0.5966666666666667 [0.5333333333333333 0.63333...,-0.03322472114049386 [-0.2161898371387133 0.13...,0.4481012658227848 [0.4 0.5],0.0 [0.0 0.0]
17,SUB,Chinese,Deepseek V3.2,0.13666666666666666 [0.03333333333333333 0.283...,0.008387187563794113 [-0.16977232529395878 0.2...,0.1225 [0.075 0.175],0.026905918919070636 [0.009000000000000001 0.0...
18,SUB,Chinese,Qwen3 30B-A3B 2507,0.15333333333333335 [0.08333333333333333 0.2],0.08698745956078249 [-0.10430279343698577 0.28...,0.05 [0.05 0.05],0.023916372372507235 [0.007 0.09052499999999998]
19,SUB,EU,EuroLLM 9B,0.3781818181818182 [0.2196212121212121 0.55759...,0.26268218520110953 [-0.04440886254583761 0.81...,0.15517241379310345 [0.05714285714285714 0.263...,0.03886410510532426 [0.01556625 0.144000000000...
20,SUB,EU,Mistral Large 2512,0.18166666666666667 [0.16666666666666666 0.233...,0.04075200544490698 [-0.16284663000540558 0.35...,0.17543859649122806 [0.15 0.20512820512820512],0.026905918919070636 [0.009000000000000001 0.1...
21,SUB,Russian,GigaChat 20B-A3B,0.34317819435466496 [0.2166666666666667 0.4833...,0.8822372703538415 [0.4070396617882132 1.97884...,0.10796915167095116 [0.05128205128205128 0.179...,0.04185365165188766 [0.016 0.15667499999999984]
22,SUB,Russian,QVikhr 3 8B,0.29166666666666663 [0.21666666666666665 0.333...,0.028156830013340888 [-0.17250770095464418 0.3...,0.075 [0.05 0.1],0.0029895465465634044 [0.0 0.015000000000000001]
23,SUB,Russian,T-Pro 2.0,0.23333333333333334 [0.11666666666666665 0.35],0.08369414655645985 [-0.1445401354437726 0.400...,0.0775 [0.025 0.125],0.014947732732817022 [0.003372500000000001 0.0...
24,SUB,Russian,YandexGPT 5 Lite 8B,0.42000000000000004 [0.4166666666666667 0.4333...,0.13322291367665803 [-0.08088279206430307 0.41...,0.025 [0.025 0.025],0.02092682582594383 [0.0055 0.08257499999999994]
25,SUB,USA,Claude Haiku 4.5,0.19333333333333333 [0.13333333333333333 0.2],0.24881154896634686 [-0.04359932831189493 0.67...,0.0775 [0.075 0.1],0.017937279279380425 [0.004447500000000001 0.0...
26,SUB,USA,GPT5 Mini,0.10833333333333332 [0.06666666666666667 0.133...,0.045375550856494536 [-0.09793463235824545 0.2...,0.028645833333333332 [0.025 0.05263157894736842],0.0029895465465634044 [0.0 0.015000000000000001]
27,SUB,USA,Gemini 3 Flash Prev,0.14333333333333334 [0.08333333333333333 0.15],0.133222913676658 [-0.12300582305494831 0.4252...,0.0777479892761394 [0.05263157894736842 0.0857...,0.023916372372507235 [0.007 0.08904999999999996]
28,SUB,USA,Grok 4.1 Fast,0.225 [0.2 0.3],0.29504700308222237 [-0.03304555109992949 0.75...,0.125 [0.075 0.15],0.07473866366408512 [0.03227142857142857 0.269...
29,SUB,USA,Olmo 3.1 32B,0.32166666666666666 [0.18333333333333332 0.45],0.17021127696935845 [-0.07849675413403079 0.57...,0.0975 [0.05 0.15],0.014947732732817022 [0.0033333333333333335 0....
30,SUB,USA,Olmo3 7B Base,0.374008492130623 [0.21658333333333332 0.55691...,0.15653578656178205 [-0.11935464275420134 0.63...,0.23076923076923078 [0.0 0.5714285714285714],0.022996511896641574 [0.006340794845180422 0.0...
31,SUB,USA,Olmo3 7B Instruct SFT,0.3616666666666667 [0.21666666666666665 0.4833...,0.3793679329613445 [0.024973484166194306 1.030...,0.1326530612244898 [0.07692307692307693 0.1842...,0.0029895465465634044 [0.0 0.015000000000000001]
32,SUB,USA,Olmo3 7B Instruct DPO,0.30166666666666664 [0.18333333333333332 0.416...,0.1360872959889215 [-0.10223361734973062 0.473...,0.1325 [0.1 0.175],0.017937279279380425 [0.004895000000000001 0.07]
33,SUB,USA,Olmo3 7B Instruct RLVR,0.35 [0.2333333333333333 0.45],0.0826773748550653 [-0.13589143517403857 0.382...,0.1275 [0.125 0.15],0.005979093093126809 [0.0 0.03276249999999999]
34,CONV,Chinese,Deepseek V3.2,0.33 [0.25 0.4666666666666666],0.13784645908824555 [-0.10171756291973576 0.43...,0.19 [0.15 0.225],0.004769758246972892 [0.0 0.048]
35,CONV,Chinese,Qwen3 30B-A3B 2507,0.20666666666666664 [0.18333333333333332 0.283...,0.17021127696935845 [-0.0749219354582936 0.573...,0.205 [0.2 0.225],0.0015400555658441834 [0.0 0.04]
36,CONV,EU,EuroLLM 9B,0.48280701754385963 [0.31666666666666665 0.625...,0.5724597277774754 [0.27776606323320574 1.2088...,0.2714285714285714 [0.15625 0.3939593301435406],0.007999460928101602 [0.0 0.0520625]
37,CONV,EU,Mistral Large 2512,0.32333333333333336 [0.26666666666666666 0.366...,-0.033224721140493865 [-0.22020641746471714 0....,0.20512820512820512 [0.20512820512820512 0.205...,0.0 [0.0 0.021083333333333336]
38,CONV,Russian,GigaChat 20B-A3B,0.49551282051282053 [0.3666666666666667 0.6333...,0.9978259056435302 [0.48773857817339655 2.1363...,0.24040920716112532 [0.17491071428571428 0.307...,0.007999460928101602 [0.0 0.050666666666666665]
39,CONV,Russian,QVikhr 3 8B,0.475 [0.3833333333333333 0.55],0.15085603018562757 [-0.11315746918317625 0.46...,0.235 [0.225 0.275],0.0 [0.0 0.02]
40,CONV,Russian,T-Pro 2.0,0.32166666666666666 [0.26666666666666666 0.416...,0.04122621523071082 [-0.18084266615307262 0.37...,0.1875 [0.15 0.225],0.0 [0.0 0.021416666666666667]
41,CONV,Russian,YandexGPT 5 Lite 8B,0.325 [0.31666666666666665 0.33333333333333337],0.19795254943888377 [-0.10297958642930827 0.60...,0.2525 [0.2 0.3],0.0 [0.0 0.02]
42,CONV,USA,Claude Haiku 4.5,0.2033333333333333 [0.15 0.2333333333333333],0.12397582285348292 [-0.06526131956252984 0.37...,0.2512820512820513 [0.23076923076923078 0.2564...,0.0 [0.0 0.008]
43,CONV,USA,GPT5 Mini,0.215 [0.13333333333333333 0.2833333333333333],0.11010518661872024 [-0.10108149297455549 0.38...,0.1912568306010929 [0.1388888888888889 0.25],0.0 [0.0 0.009000000000000001]
44,CONV,USA,Gemini 3 Flash Prev,0.10499999999999998 [0.09999999999999999 0.15],0.32741182096333526 [0.052398876596655306 0.79...,0.21195652173913043 [0.18421052631578946 0.235...,0.0 [0.0 0.026083333333333333]
45,CONV,USA,Grok 4.1 Fast,0.27999999999999997 [0.2 0.33333333333333337],0.47536527413413693 [0.1953423541750044 1.0969...,0.21 [0.175 0.25],0.007999460928101602 [0.0 0.054125000000000006]
46,CONV,USA,Olmo 3.1 32B,0.41 [0.31666666666666665 0.5],0.3576607790798233 [0.07407282390470389 0.8724...,0.1875 [0.15 0.225],0.0 [0.0 0.015075000000000002]
47,CONV,USA,Olmo3 7B Base,0.42533973533973535 [0.2833333333333333 0.5773...,0.2907039225127293 [-0.05069832882125752 0.858...,0.30985915492957744 [0.0 0.6666666666666666],0.0 [0.0 0.023235286396807896]
48,CONV,USA,Olmo3 7B Instruct SFT,0.485 [0.35 0.6166666666666666],0.5897784317768119 [0.3317645494129939 1.20120...,0.1945945945945946 [0.1282051282051282 0.27777...,0.0 [0.0 0.01890625]
49,CONV,USA,Olmo3 7B Instruct DPO,0.5816666666666667 [0.4833333333333333 0.65],0.5173657160662894 [0.22089824933019453 1.0949...,0.14690721649484537 [0.10256410256410256 0.205...,0.0 [0.0 0.01635416666666667]
50,CONV,USA,Olmo3 7B Instruct RLVR,0.5433333333333333 [0.43291666666666667 0.6333...,0.5077300920152498 [0.19878391630627182 1.0666...,0.1712846347607053 [0.125 0.225],0.0 [0.0 0.024]

In [15]:
print(df_to_latex(df_3d, caption="3D Results.", label="tab:3d-results", fit="resize"))

\begin{table}[ht]
\centering
\caption{3D Results.}
\label{tab:3d-results}
\setlength{\tabcolsep}{4pt}
\resizebox{\textwidth}{!}{%
\begin{tabular}{ll|cccc|cccc|cccc}
\toprule
 & & \multicolumn{4}{c}{AGR} & \multicolumn{4}{c}{SUB} & \multicolumn{4}{c}{CONV} \\
\cmidrule(lr){3-6} \cmidrule(lr){7-10} \cmidrule(lr){11-14}
 & & Psyc (Closed) & Psyc (Open) & Behavioral & Realistic & Psyc (Closed) & Psyc (Open) & Behavioral & Realistic & Psyc (Closed) & Psyc (Open) & Behavioral & Realistic \\
\midrule
\multirow{2}{*}{Chinese} & Deepseek V3.2 & \cellcolor[HTML]{F6D5C6}21.3 [\phantom{0}8.3 36.7] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}\phantom{0}6.4] & \cellcolor[HTML]{F4A887}48.0 [40.0 55.0] & \cellcolor[HTML]{F7F5F5}0.8 [0.0 2.7] & \cellcolor[HTML]{F6E0D6}13.7 [\phantom{0}3.3 28.3] & \cellcolor[HTML]{F7F5F5}\phantom{0}0.8 [\phantom{0}0.0 \phantom{0}23.8] & \cellcolor[HTML]{F6E3DB}12.2 [\phantom{0}7.5 17.5] & \cellcolor[HTML]{F7F2F0}2.7 [0.9 10.0] & \cellcolor[HTML]{F5C1AA}33.0 [25.0 46.7] & \cellcolor[HTML]{F6E0D6}13.8 [\phantom{0}0.0 \phantom{0}43.1] & \cellcolor[HTML]{F6D8CB}19.0 [15.0 22.5] & \cellcolor[HTML]{F7F7F7}0.5 [0.0 4.8] \\
 & Qwen3 30B-A3B 2507 & \cellcolor[HTML]{F6E5DD}11.3 [\phantom{0}5.0 18.3] & \cellcolor[HTML]{F6E5DD}11.0 [0.0 \phantom{0}53.7] & \cellcolor[HTML]{F4A582}50.2 [47.5 52.5] & \cellcolor[HTML]{F7F5F5}0.8 [0.0 2.8] & \cellcolor[HTML]{F6DED4}15.3 [\phantom{0}8.3 20.0] & \cellcolor[HTML]{F6E8E2}\phantom{0}8.7 [\phantom{0}0.0 \phantom{0}28.7] & \cellcolor[HTML]{F7EFEB}\phantom{0}5.0 [\phantom{0}5.0 \phantom{0}5.0] & \cellcolor[HTML]{F7F4F2}2.4 [0.7 \phantom{0}9.1] & \cellcolor[HTML]{F6D5C6}20.7 [18.3 28.3] & \cellcolor[HTML]{F6DBCF}17.0 [\phantom{0}0.0 \phantom{0}57.4] & \cellcolor[HTML]{F6D6C8}20.5 [20.0 22.5] & \cellcolor[HTML]{F7F7F7}0.2 [0.0 4.0] \\
\midrule
\multirow{2}{*}{EU} & EuroLLM 9B & \cellcolor[HTML]{F4AA89}47.0 [30.8 63.3] & \cellcolor[HTML]{F6E0D6}13.8 [0.0 \phantom{0}56.2] & \cellcolor[HTML]{F4A582}49.7 [36.1 64.1] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F5B99E}37.8 [22.0 55.8] & \cellcolor[HTML]{F5CCBA}26.3 [\phantom{0}0.0 \phantom{0}81.8] & \cellcolor[HTML]{F6DDD2}15.5 [\phantom{0}5.7 26.3] & \cellcolor[HTML]{F7F0EE}3.9 [1.6 14.4] & \cellcolor[HTML]{F4A887}48.3 [31.7 62.6] & \cellcolor[HTML]{EE8E74}57.2 [27.8 100.0] & \cellcolor[HTML]{F5CBB8}27.1 [15.6 39.4] & \cellcolor[HTML]{F7F5F5}0.8 [0.0 5.2] \\
 & Mistral Large 2512 & \cellcolor[HTML]{F5C7B3}28.5 [28.3 30.0] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}\phantom{0}8.8] & \cellcolor[HTML]{F4AC8B}46.0 [41.0 48.7] & \cellcolor[HTML]{F7F5F5}1.0 [0.0 3.5] & \cellcolor[HTML]{F6D9CD}18.2 [16.7 23.3] & \cellcolor[HTML]{F7F0EE}\phantom{0}4.1 [\phantom{0}0.0 \phantom{0}35.5] & \cellcolor[HTML]{F6D9CD}17.5 [15.0 20.5] & \cellcolor[HTML]{F7F2F0}2.7 [0.9 10.8] & \cellcolor[HTML]{F5C3AC}32.3 [26.7 36.7] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [\phantom{0}0.0 \phantom{0}16.9] & \cellcolor[HTML]{F6D5C6}20.5 [20.5 20.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.1] \\
\midrule
\multirow{4}{*}{Russian} & GigaChat 20B-A3B & \cellcolor[HTML]{F5B599}40.1 [30.0 53.3] & \cellcolor[HTML]{F5BCA3}36.4 [0.0 100.0] & \cellcolor[HTML]{F5B79C}39.0 [30.0 48.7] & \cellcolor[HTML]{F7F5F5}1.0 [0.0 3.2] & \cellcolor[HTML]{F5BFA7}34.3 [21.7 48.3] & \cellcolor[HTML]{D42838}88.2 [40.7 100.0] & \cellcolor[HTML]{F6E5DD}10.8 [\phantom{0}5.1 17.9] & \cellcolor[HTML]{F7F0EE}4.2 [1.6 15.7] & \cellcolor[HTML]{F4A582}49.6 [36.7 63.3] & \cellcolor[HTML]{CA0020}99.8 [48.8 100.0] & \cellcolor[HTML]{F6D0BF}24.0 [17.5 30.8] & \cellcolor[HTML]{F7F5F5}0.8 [0.0 5.1] \\
 & QVikhr 3 8B & \cellcolor[HTML]{F5C3AC}31.7 [31.7 31.7] & \cellcolor[HTML]{F7F5F5}\phantom{0}1.1 [0.0 \phantom{0}16.8] & \cellcolor[HTML]{F5BCA3}35.8 [32.5 40.0] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F5C7B3}29.2 [21.7 33.3] & \cellcolor[HTML]{F7F2F0}\phantom{0}2.8 [\phantom{0}0.0 \phantom{0}30.0] & \cellcolor[HTML]{F7EAE4}\phantom{0}7.5 [\phantom{0}5.0 10.0] & \cellcolor[HTML]{F7F7F7}0.3 [0.0 \phantom{0}1.5] & \cellcolor[HTML]{F4A887}47.5 [38.3 55.0] & \cellcolor[HTML]{F6DED4}15.1 [\phantom{0}0.0 \phantom{0}46.6] & \cellcolor[HTML]{F6D0BF}23.5 [22.5 27.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.0] \\
 & T-Pro 2.0 & \cellcolor[HTML]{F5BEA5}35.2 [28.3 46.7] & \cellcolor[HTML]{F7F0EE}\phantom{0}4.2 [0.0 \phantom{0}33.8] & \cellcolor[HTML]{F1987A}54.2 [47.5 62.5] & \cellcolor[HTML]{F7F7F7}0.3 [0.0 1.2] & \cellcolor[HTML]{F6D1C1}23.3 [11.7 35.0] & \cellcolor[HTML]{F7EAE4}\phantom{0}8.4 [\phantom{0}0.0 \phantom{0}40.1] & \cellcolor[HTML]{F7EAE4}\phantom{0}7.8 [\phantom{0}2.5 12.5] & \cellcolor[HTML]{F7F5F5}1.5 [0.3 \phantom{0}6.0] & \cellcolor[HTML]{F5C3AC}32.2 [26.7 41.7] & \cellcolor[HTML]{F7F0EE}\phantom{0}4.1 [\phantom{0}0.0 \phantom{0}37.8] & \cellcolor[HTML]{F6D8CB}18.8 [15.0 22.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.1] \\
 & YandexGPT 5 Lite 8B & \cellcolor[HTML]{F1987A}53.7 [48.3 55.0] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}\phantom{0}5.3] & \cellcolor[HTML]{F29E7E}51.5 [50.0 52.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F4B295}42.0 [41.7 43.3] & \cellcolor[HTML]{F6E2D9}13.3 [\phantom{0}0.0 \phantom{0}41.8] & \cellcolor[HTML]{F7F4F2}\phantom{0}2.5 [\phantom{0}2.5 \phantom{0}2.5] & \cellcolor[HTML]{F7F4F2}2.1 [0.5 \phantom{0}8.3] & \cellcolor[HTML]{F5C3AC}32.5 [31.7 33.3] & \cellcolor[HTML]{F6D6C8}19.8 [\phantom{0}0.0 \phantom{0}60.6] & \cellcolor[HTML]{F6CEBC}25.2 [20.0 30.0] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.0] \\
\midrule
\multirow{9}{*}{USA} & Claude Haiku 4.5 & \cellcolor[HTML]{F6E5DD}10.7 [\phantom{0}8.3 15.0] & \cellcolor[HTML]{F7EDE9}\phantom{0}5.9 [0.0 \phantom{0}26.7] & \cellcolor[HTML]{F5C9B5}28.3 [22.8 34.3] & \cellcolor[HTML]{F7F7F7}0.3 [0.0 1.2] & \cellcolor[HTML]{F6D8CB}19.3 [13.3 20.0] & \cellcolor[HTML]{F6CEBC}24.9 [\phantom{0}0.0 \phantom{0}67.9] & \cellcolor[HTML]{F7EAE4}\phantom{0}7.8 [\phantom{0}7.5 10.0] & \cellcolor[HTML]{F7F4F2}1.8 [0.4 \phantom{0}7.2] & \cellcolor[HTML]{F6D6C8}20.3 [15.0 23.3] & \cellcolor[HTML]{F6E3DB}12.4 [\phantom{0}0.0 \phantom{0}37.3] & \cellcolor[HTML]{F6CEBC}25.1 [23.1 25.6] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.8] \\
 & GPT5 Mini & \cellcolor[HTML]{F6DED4}15.2 [\phantom{0}3.3 30.0] & \cellcolor[HTML]{F6E7E0}\phantom{0}9.6 [0.0 \phantom{0}49.5] & \cellcolor[HTML]{F5C3AC}32.5 [23.3 42.4] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F6E5DD}10.8 [\phantom{0}6.7 13.3] & \cellcolor[HTML]{F7EFEB}\phantom{0}4.5 [\phantom{0}0.0 \phantom{0}27.8] & \cellcolor[HTML]{F7F2F0}\phantom{0}2.9 [\phantom{0}2.5 \phantom{0}5.3] & \cellcolor[HTML]{F7F7F7}0.3 [0.0 \phantom{0}1.5] & \cellcolor[HTML]{F6D3C4}21.5 [13.3 28.3] & \cellcolor[HTML]{F6E5DD}11.0 [\phantom{0}0.0 \phantom{0}38.2] & \cellcolor[HTML]{F6D8CB}19.1 [13.9 25.0] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.9] \\
 & Gemini 3 Flash Prev & \cellcolor[HTML]{F7F5F5}\phantom{0}1.3 [\phantom{0}0.0 \phantom{0}8.3] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}\phantom{0}0.0] & \cellcolor[HTML]{F5BCA3}36.5 [30.0 41.9] & \cellcolor[HTML]{F7F5F5}0.5 [0.0 2.0] & \cellcolor[HTML]{F6E0D6}14.3 [\phantom{0}8.3 15.0] & \cellcolor[HTML]{F6E2D9}13.3 [\phantom{0}0.0 \phantom{0}42.5] & \cellcolor[HTML]{F7EAE4}\phantom{0}7.8 [\phantom{0}5.3 \phantom{0}8.6] & \cellcolor[HTML]{F7F4F2}2.4 [0.7 \phantom{0}8.9] & \cellcolor[HTML]{F6E7E0}10.5 [10.0 15.0] & \cellcolor[HTML]{F5C1AA}32.7 [\phantom{0}5.2 \phantom{0}80.0] & \cellcolor[HTML]{F6D5C6}21.2 [18.4 23.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.6] \\
 & Grok 4.1 Fast & \cellcolor[HTML]{F5C1AA}33.0 [21.7 41.7] & \cellcolor[HTML]{F6D5C6}20.7 [0.4 \phantom{0}54.6] & \cellcolor[HTML]{F09478}55.0 [50.0 60.0] & \cellcolor[HTML]{F7F2F0}2.8 [0.9 8.1] & \cellcolor[HTML]{F6D3C4}22.5 [20.0 30.0] & \cellcolor[HTML]{F5C6B1}29.5 [\phantom{0}0.0 \phantom{0}75.1] & \cellcolor[HTML]{F6E3DB}12.5 [\phantom{0}7.5 15.0] & \cellcolor[HTML]{F7ECE7}7.5 [3.2 27.0] & \cellcolor[HTML]{F5C9B5}28.0 [20.0 33.3] & \cellcolor[HTML]{F4A887}47.5 [19.5 100.0] & \cellcolor[HTML]{F6D5C6}21.0 [17.5 25.0] & \cellcolor[HTML]{F7F5F5}0.8 [0.0 5.4] \\
 & Olmo 3.1 32B & \cellcolor[HTML]{F5C9B5}28.0 [21.7 35.0] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}\phantom{0}7.7] & \cellcolor[HTML]{F4A582}50.0 [42.5 55.0] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F5C3AC}32.2 [18.3 45.0] & \cellcolor[HTML]{F6DBCF}17.0 [\phantom{0}0.0 \phantom{0}57.9] & \cellcolor[HTML]{F6E7E0}\phantom{0}9.8 [\phantom{0}5.0 15.0] & \cellcolor[HTML]{F7F5F5}1.5 [0.3 \phantom{0}5.6] & \cellcolor[HTML]{F5B497}41.0 [31.7 50.0] & \cellcolor[HTML]{F5BCA3}35.8 [\phantom{0}7.4 \phantom{0}87.2] & \cellcolor[HTML]{F6D8CB}18.8 [15.0 22.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 1.5] \\
 & Olmo3 7B Base & \cellcolor[HTML]{F4A582}49.6 [33.3 68.3] & \cellcolor[HTML]{F6E3DB}11.8 [0.0 \phantom{0}57.5] & \cellcolor[HTML]{F4AC8B}46.1 [12.5 80.0] & \cellcolor[HTML]{F7F5F5}0.6 [0.0 2.2] & \cellcolor[HTML]{F5BAA0}37.4 [21.7 55.7] & \cellcolor[HTML]{F6DDD2}15.7 [\phantom{0}0.0 \phantom{0}63.7] & \cellcolor[HTML]{F6D1C1}23.1 [\phantom{0}0.0 57.1] & \cellcolor[HTML]{F7F4F2}2.3 [0.6 \phantom{0}8.8] & \cellcolor[HTML]{F4B092}42.5 [28.3 57.7] & \cellcolor[HTML]{F5C7B3}29.1 [\phantom{0}0.0 \phantom{0}85.8] & \cellcolor[HTML]{F5C4AE}31.0 [\phantom{0}0.0 66.7] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.3] \\
 & Olmo3 7B Instruct SFT & \cellcolor[HTML]{EC846E}60.0 [43.3 75.0] & \cellcolor[HTML]{F7F5F5}\phantom{0}0.8 [0.0 \phantom{0}20.8] & \cellcolor[HTML]{F4AA89}47.2 [37.8 56.8] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F5BCA3}36.2 [21.7 48.3] & \cellcolor[HTML]{F5B99E}37.9 [\phantom{0}2.5 100.0] & \cellcolor[HTML]{F6E2D9}13.3 [\phantom{0}7.7 18.4] & \cellcolor[HTML]{F7F7F7}0.3 [0.0 \phantom{0}1.5] & \cellcolor[HTML]{F4A887}48.5 [35.0 61.7] & \cellcolor[HTML]{EC8770}59.0 [33.2 100.0] & \cellcolor[HTML]{F6D8CB}19.5 [12.8 27.8] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 1.9] \\
 & Olmo3 7B Instruct DPO & \cellcolor[HTML]{F4A582}50.5 [36.7 61.7] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}17.1] & \cellcolor[HTML]{F4AD8E}44.6 [38.5 50.0] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F5C6B1}30.2 [18.3 41.7] & \cellcolor[HTML]{F6E0D6}13.6 [\phantom{0}0.0 \phantom{0}47.3] & \cellcolor[HTML]{F6E2D9}13.2 [10.0 17.5] & \cellcolor[HTML]{F7F4F2}1.8 [0.5 \phantom{0}7.0] & \cellcolor[HTML]{ED8B72}58.2 [48.3 65.0] & \cellcolor[HTML]{F29E7E}51.7 [22.1 100.0] & \cellcolor[HTML]{F6DED4}14.7 [10.3 20.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 1.6] \\
 & Olmo3 7B Instruct RLVR & \cellcolor[HTML]{EC846E}59.7 [53.3 63.3] & \cellcolor[HTML]{F7F7F7}\phantom{0}0.0 [0.0 \phantom{0}13.6] & \cellcolor[HTML]{F4AD8E}44.8 [40.0 50.0] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 0.0] & \cellcolor[HTML]{F5BEA5}35.0 [23.3 45.0] & \cellcolor[HTML]{F7EAE4}\phantom{0}8.3 [\phantom{0}0.0 \phantom{0}38.2] & \cellcolor[HTML]{F6E2D9}12.8 [12.5 15.0] & \cellcolor[HTML]{F7F5F5}0.6 [0.0 \phantom{0}3.3] & \cellcolor[HTML]{F1987A}54.3 [43.3 63.3] & \cellcolor[HTML]{F3A280}50.8 [19.9 100.0] & \cellcolor[HTML]{F6DBCF}17.1 [12.5 22.5] & \cellcolor[HTML]{F7F7F7}0.0 [0.0 2.4] \\
\bottomrule
\end{tabular}
}
\end{table}